#Aditya Joshi
#Rosalind - The Billion year war


def reverse_complement(dna):
    new_dna = ""
    rev = dna[::-1]
    for element in rev:
        if element == "A":
            new_dna = new_dna + "T"
        if element == "T":
            new_dna = new_dna + "A"
        if element == "C":
            new_dna = new_dna + "G"
        if element == "G":
            new_dna = new_dna + "C"
    return new_dna==dna



def compute(dna):
    for x in range(len(dna)):
        for y in range(x,len(dna)+1):
            now = dna[x:y]
            ans = reverse_complement(now)
            if ans == True:
                if 4 <= len(now) <=12:
                    print x+1,len(now)
            
            

print compute("""CGCGGAGCTCGGAATACTTGTCTCTACGATTCCTCACAGTCTATCCGCTGCCGCGGTTGTCGGTTTCTCCAAGCCTCTACTCTTCATTTTATCAACGGCCCTAGTATTCATAGTATAGTATCTGGAAGCCTCCACGCCTCATTCGCTATCCTGTGTATCTAACCCGACTGATCGATTTGGACAGAGTGCTCGACTTGGTCTATTTCCTGTCGATTCTTGAGGCGGCTTTGGATATTCCTCGTAGTTCGGCTTGTCTATCTAAATCGTAGTAACAAACAGATGAGACGAGACCACAGCTACACTTACGTTGCACCTGGGCGGAACTGATTCTAGGGTTGAGCACAAAGCTTGATGTACCAAGGATCAGATTGAGAGCATTACGGGGTGAGCCCGGTGTAGCTGCTTGATAACTTCATTGCTCCGTACAGCGGGCAGGAGGCGCGACCGGCCGGTCTTAGGATTCGTTTCGTCAACAAAGCGGCGTTTTCAAATGGCTGGCTCAATGAGTATGGATCGGTCCGAGAAAGCCAGTAGATCGTTGATTGCGAGCCTGTCTGCCGGGAGGGGGAACAGCGTTGCCGGCCTTTCCCTCTGGAACCACACCCCACTACACCCTGATGGTAGTTTTTGATATATGCATACCATAGGTCTCCTCGCCACTTAGGAGACACCCAACGTATGCTCGCCACCTGTCTGCAGTCTATCCTGTGAGGTGCCATCTTAGTCACGGAGGACACTCAGAGATGACGTCTTATTATACAATAATGGGACCTCATGCGGGAATAGAGCGCACTGGGCTATATCGCATGTCATTTGCGTCGCCCCGGTCCGAGAACCTCATATAGAAAAACCCGGATCCCCAAAAGATTTTCTCTGGCTGGCGCTCAGAATACGCG""")

