#Aditya Joshi
#Computational Biology
#Finding a Motif in DNA 1.0
#Brute Force solution


def motif(dna,subdna):
    
    buffer = len(subdna)
    points = []
    for x in range(len(dna)):
        if dna[x:x+buffer] == subdna:
            points += [x]
    revised = [x+1 for x in points]
    return revised
        
#This is the dna sequence    
long = """GGGGGTTACGTGGTTACGGTGGGGTTACGTGGTTACGGGGGTTACGGGTTACGGGTTACGTACCGGGGTTACGGGGTTACGGGTTACGTGGGTTACGCCGGTCATGGTTACGGCAGCCGGGTTACGTGAGGTTACGGGGGGTTACGGAAGGTTACGTTACCATCGGTTACGGTAAAGGTTACGTGGTTACGAAGGGGTTACGTTGGTTACGGGTTACGGGTTACGGGGTTACGCGGCATGGTTACGTGGACCATGGGTTACGTTGGTTACGGATGGTTACGGGTTACGTTATGCGGGTTACGGCATGGTTACGTGGTTACGAGGTTACGAGCACCCGGTTACGTCTTGTGGTTACGCCGGGCACGGTTACGTTGGTTACGATGGTTACGGTCGGTTACGTGACAGACGGTTACGGGTTACGAGGGTTACGAGGTTACGTCGGTTACGACGGTTACGAACACTGGTTACGAGGCGGTTACGGGTTACGCGGGTTACGCCCGGTTACGGGTTACGCCGGAGGTTACGCATGGTTACGGGTTACGCTCGGTTACGGAGGTTACGTGGTTACGTTGGTTACGCGGTTACGTGTAGGTTACGGGGTTACGGGTTACGTAATGGTCCGGGTTACGCCAGGTTACGGGTTACGCCGGTTACGCCAACGGTTACGAAAGGTTACGAACGGTTACGATGGTTACGGGGAGGTTACGGGTTACGCTGCCTAGAGTGGTTACGCGACGTGGTTACGGGTTACGGGTTACGGGTTACGGTTCCGGTTACGCGGTTACGTAGGTTACGTTCCGGTTACGACGGTTACGCGGTTACGCGGTTACGCTACGCCGGTTACGTGATCGGTTACGC"""

#This is the subset that is to be found
short = "GGTTACGGG"

print motif(long,short)
